// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2sfsw-Ffmvr8LUDCIZ5dv7ZclEecnvGM',
    appId: '1:105400614461:web:c0abb2d804f0aec68c3454',
    messagingSenderId: '105400614461',
    projectId: 'tracker-f10e0',
    authDomain: 'tracker-f10e0.firebaseapp.com',
    storageBucket: 'tracker-f10e0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB67M_xG1VTzEbWHXLvo9r8v__WE9KCYJQ',
    appId: '1:105400614461:android:52615ac9db8862a18c3454',
    messagingSenderId: '105400614461',
    projectId: 'tracker-f10e0',
    storageBucket: 'tracker-f10e0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBu0Yyx7Z9gpeGEU7c5IIsqyA4oHScgFA4',
    appId: '1:105400614461:ios:1da0449ab59b626a8c3454',
    messagingSenderId: '105400614461',
    projectId: 'tracker-f10e0',
    storageBucket: 'tracker-f10e0.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBu0Yyx7Z9gpeGEU7c5IIsqyA4oHScgFA4',
    appId: '1:105400614461:ios:1da0449ab59b626a8c3454',
    messagingSenderId: '105400614461',
    projectId: 'tracker-f10e0',
    storageBucket: 'tracker-f10e0.appspot.com',
    iosBundleId: 'com.example.app',
  );
}
